### ISSUE TITLE
Avoid putting unused .d.ts files into compiled extensions

### ISSUE THREAD

**Issue by jhurliman** [foxglove/create-foxglove-extension#101]
With these flags in the base tsconfig.json:

```json
{
  "composite": false,
  "declaration": false
}
```

**Comment by defunctzombie** [comment]
Are these causing an issue - or are you proposing they are noise that doesn't need to exist in the extension package?

**Comment by foxymiles** [comment]
@jhurliman Can you expand on this a bit? I just tried making a new extension and don't see anything like this in the generated files.

**Comment by foxymiles** [comment]
Oh I see you're suggesting those options as a fix.
