### ISSUE TITLE
Webpack configuration for file loader

### ISSUE THREAD

**Issue by emresiimseek** [foxglove/create-foxglove-extension#102]
**Description**

Like below I configured my webpack config.ts file for file-loader.

```typescript
const path = require("path");

module.exports = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.css$/i,
      use: ["style-loader", "css-loader"],
    });

    config.module.rules.push({
      test: /\.(png|jpe?g|gif)$/i,
      use: [
        {
          loader: "file-loader",
          options: {
            name: "[path][name].[ext]",
            outputPath: "images",
            publicPath: "assets",
          },
        },
      ],
    });

    return config;
  },
};

``` 
But after local-install and package my extension it seems my image file is broken. What am I missing?
Foxglove .foxe package mechanism can package image files?
![image](https://user-images.githubusercontent.com/24704795/236749528-d19ecfb9-a194-42cf-a8b7-197cccc95630.png)

- Version:1.43.0
- Platform:Web

**Steps To Reproduce**

**Expected Behavior**

**Comment by defunctzombie** [comment]
Please share some sample code showing how you are using the file in your extension.

**Comment by emresiimseek** [comment]
> Please share some sample code showing how you are using the file in your extension.
Yes, sure. This is an example.

![image](https://user-images.githubusercontent.com/24704795/237018906-3ceb91e0-a4db-4ada-8dc4-980bdc32574d.png)

**Comment by emresiimseek** [comment]
![image](https://user-images.githubusercontent.com/24704795/237024204-5fb71b33-57d9-4c15-a8a0-b929b44dbd90.png)
![image](https://user-images.githubusercontent.com/24704795/237024243-4bc9090f-3165-468d-aacb-a996c06919da.png)

**Comment by foxymiles** [comment]
<img width="621" alt="Screenshot 2023-05-10 at 11 05 05 AM" src="https://github.com/foxglove/create-foxglove-extension/assets/93935560/3a4c03d6-4bac-42c5-94af-d83e56e7c098">

In this screenshot it looks like you have a file with `.png` extension that is actually JS re-exporting a png file. I'm not sure it will work like this. What happens if you directly import the png in the file you use it in?

**Comment by foxymiles** [comment]
For a working example of loading a png you can refer to this example: 
https://github.com/foxglove/create-foxglove-extension/tree/main/examples/custom-image-extension

**Comment by emresiimseek** [comment]
The example was very helpful. It works now, thanks.

**Comment by foxymiles** [comment]
Glad to hear you got it working!
