### ISSUE TITLE
Conflicting build instructions

### ISSUE THREAD

**Issue by jkuszmaul** [foxglove/create-foxglove-extension#108]
**Description**

If I attempt to follow the build instructions at https://foxglove.dev/docs/studio/extensions/getting-started and https://foxglove.dev/docs/studio/extensions/local-development on a clean-ish Ubuntu 22.04 system, then when I attempt to run a `yarn local-install` (or `yarn build` or anything using `yarn`) I end up getting errors about providing typescript (`ts-loader` requests `typescript` as a peer dependency):

```
$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ create-foxglove-extension@npm:0.8.4 doesn't provide typescript (p73fa3), requested by ts-loader
...
$ yarn build
Building...
Error: build failed: Errors:
ModuleNotFoundError: Module not found: Error: Can't resolve 'ts-loader' 
```

(note that this computer does not have a typescript compiler installed globally; installing it just resulted in other errors).

The README in this repository suggests using `npm install` rather than `yarn`. This seems to produce fewer errors.

**Expected Behavior**

I can identify which instructions to follow, and follow them on an otherwise clean machine and produce an extension without any errors.

**Comment by defunctzombie** [comment]
Indeed there are inconsistencies here. We'll go through the process and get these fixed up. We've moved our starter recommendations to use `npm` since `yarn` is yet-another step for folks beyond installing node.

**Comment by foxymiles** [comment]
Closed by https://github.com/foxglove/website/pull/1167

**Comment by jameskuszmaul-brt** [comment]
@foxymiles FYI https://foxglove.dev/docs/studio/extensions/getting-started still references `yarn` as a dependency that you should install (even though https://foxglove.dev/docs/studio/extensions/local-development now references `npm`). Is that expected?

**Comment by foxymiles** [comment]
Oops nope that should also be removed. https://github.com/foxglove/website/pull/1170
