### ISSUE TITLE
Possible bug? Custom panel installing & showing up on Desktop app, but not webapp

### ISSUE THREAD

**Issue by P15V** [foxglove/create-foxglove-extension#113]
Hello Foxglove Community,

Hope all is well with whoever reads this! 

Facing a issue I'm not able to find much (any at all) info about googling around.

I'm working on a whole audio streaming panel, to stream audio from a playing rostopic to a web browser interface. 

I have some mostly working code I changed to fit Foxgloves schema, did the steps to yarn install, showed up in the desktop app. Did the yarn package command, got the foxe file, but when dropped into the web app; it says installed, but no panel appears in the panel selection tab. Hoping someone might be able to assist with such.

Thanks! Be well!  

- Version: 1.67.0? 
- Platform: docker, desktop app, Web browser

Steps to reproduce, Yarn package a custom foxglove extension, drag the foxe file over, says installed, but no panel shows up. 

The expected behavior would of course be the custom panel showing up like it dose with the desktop app. 

Thanks for any help at all!

**Comment by defunctzombie** [comment]
This was fixed in https://github.com/foxglove/create-foxglove-extension/pull/114
