### ISSUE TITLE
Cross-realm object access Webpack 5

### ISSUE THREAD

**Issue by PizzocaroSolomon** [foxglove/create-foxglove-extension#125]
**Description**
After installing Node.js 18, I cloned the repo, created an example folder outside the repo, got into the repo and launched "npm init foxglove-extension@latest helloworld". The package is not building and gives me the error in the screenshot I attached

- Version:1.0.1
- Platform:Ubuntu 22.04 on WSL2
<img width="345" alt="Screenshot 2024-06-28 103228" src="https://github.com/foxglove/create-foxglove-extension/assets/38542087/3b89e553-35d2-49f5-b1b1-7f059ac1affe">

**Steps To Reproduce**

**Expected Behavior**

**Comment by bryfox** [comment]
Thanks. The screenshot looks like the output of `npm audit`; we'll have to address the dependency update.

> The package is not building

This sounds like a separate problem. What command is failing, and what output are you seeing?

**Comment by bryfox** [comment]
v1.0.2 has upgraded dependencies and will no longer display the above audit warnings. Thanks for the report.

If you're still having trouble with the build step, please open a new issue which describes the steps you're taking and how it's failing.
