### ISSUE TITLE
Npm init Error

### ISSUE THREAD

**Issue by ladianchad** [foxglove/create-foxglove-extension#65]
**Description**

- Version: latest
- Platform: Ubuntu 22.04

**Steps To Reproduce**
when i run ```npm init foxglove-extension behavior_tree``` , this error shows up

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/webidl-conversions/-/webidl-conversions-3.0.1.tgz
npm ERR! 404 
npm ERR! 404  'webidl-conversions@https://packagecloud.io/github/git-lfs/npm/webidl-conversions/-/webidl-conversions-3.0.1.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kevin/.npm/_logs/2022-07-21T03_05_11_615Z-debug-0.log
```
**Expected Behavior**

**Actual Behavior**

**Comment by amacneil** [comment]
Hi - just tested this and it's working for me.

Which version of nodejs and npm are you running?

**Comment by defunctzombie** [comment]
Please make sure to run the latest version of `foxglove-extension` via:

```npm init foxglove-extension@latest behavior_tree```

**Comment by defunctzombie** [comment]
Please also provide the full terminal output that shows the command you ran.

**Comment by defunctzombie** [comment]
Closing since there's been no response on the ticket and we were not able to reproduce.
