### ISSUE TITLE
Example of loading `brion/ogv.js` inside an extension

### ISSUE THREAD

**Issue by amacneil** [foxglove/create-foxglove-extension#69]
Might not need to merge this one, but we should explore loading this package that requires a wasm blob URL.

https://github.com/foxglove/studio/issues/3401#issuecomment-1206997865

**Comment by defunctzombie** [comment]
Some PRs I made while working through making this example:

https://github.com/foxglove/create-foxglove-extension/pull/71
https://github.com/foxglove/create-foxglove-extension/pull/70

Both of these make the extension authoring experience more pleasant

**Comment by defunctzombie** [comment]
Here is an example: https://github.com/defunctzombie/studio-extension-ogv-example

It needs: https://github.com/foxglove/create-foxglove-extension/pull/70 (or the custom config added back to its config.ts)

@amacneil Should we have this in the create-foxglove-extension repo? That the end of it all the two "example" items here are how to use `wasm/inline` in `config.ts` and how to deal with emscripten specific wasm loading.

/cc @rgov

**Comment by amacneil** [comment]
I think having a "here's how to use wasm" example in this repo would be nice.

I don't think your example is good for that, because it's more specifically "how to use ogv.js" with some monkey patch hacks, and I don't think is generalizable to other libraries. So keeping it a separate repo seems fine for now.

ogv.js seems pretty well maintained, maybe worth submitting your patch upstream while we're here?

**Comment by defunctzombie** [comment]
> I think having a "here's how to use wasm" example in this repo would be nice.

There's no one-size-fits-all wasm example. emscripten uses this loader pattern where you can override `wasmBinary` and `locateFile`. Rust wasm uses different patterns: https://rustwasm.github.io/wasm-pack/book/tutorials/hybrid-applications-with-webpack/using-your-library.html

The common part would be that you need to inline your wasm.

> ogv.js seems pretty well maintained, maybe worth submitting your patch upstream while we're here?

Not something I'm keen in spending cycles on right now cause I'm sure it will need several rounds of API design or feedback from the maintainers.

**Comment by defunctzombie** [comment]
The example repo is updated to the latest version of create-foxglove-extension. It should how to load wasm for ogv.js.

I'm closing out this issue since the example works. If we think this should be moved to the `create-foxglove-extension` repo feel free to open a new issue otherwise I'm gonna consider this issue as the reference for how to do this for now.
