### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by schmogmog** [foxglove/create-foxglove-extension#73]
Hello,
I tried to make an extension, which read csv files and used therefore the packages **fs** and **csv-parse**. At first I had problems with using the **fs** package, but after updating to the newest foxglove version it works. The installation process of the extension was successful, but when I start Foxglove it tolds me that my extension is unknown and in the Developer Tools appears the error _Buffer is not defined_.

- Foxglove Version: 1.21.0
- create-foxglove-extension: 0.6.0

![grafik](https://user-images.githubusercontent.com/107186363/184130174-56a9aab6-4083-441e-93e2-bb5e97a9cbb0.png)

**Comment by jtbandes** [comment]
Extensions run in the browser, so they do not have access to APIs like `fs` and `Buffer`. In https://github.com/foxglove/create-foxglove-extension/pull/70 we configured webpack so it doesn't crash when `fs` is imported, but actually using `fs` will not work. We could provide a polyfill for Buffer as well, but you will probably have better luck if you use packages which are intended to work in the browser.

**Comment by schmogmog** [comment]
Thanks for the clarification, then I have to find other packages. 👍
