### ISSUE TITLE
`yarn local-install` does not work with Studio installed via `snap`

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/create-foxglove-extension#89]
**Description**
`yarn local-install` to install an extension for local testing with the desktop app does not work with Studio apps installed via the snap store.

**Steps To Reproduce**
1. Install Studio from the snap store
2. Run `yarn local-install` to install a sample extension
3. Open Studio (make sure to open the snap version)

Notice the extension is not installed as expected.

**Expected Behavior**
- [ideal] The extension is installed
- [alternative] The docs are clearer that `local-install` does not work with snap packages

**Comment by jtbandes** [comment]
Any idea why this happens? Is the snap sandboxed and unable to access the home folder?

**Comment by defunctzombie** [comment]
@jtbandes I don't know that a definitive answer is known yet. It might be a permission/sandboxing issue and we need to ask for this type of access for the snap package. It might be how we are looking up the "config" directory for the app.

**Comment by achim-k** [comment]
See discussion in https://github.com/foxglove/studio/pull/5280 and https://github.com/foxglove/create-foxglove-extension/pull/91. 

Closing as #91 has been merged.
